name: Release

on:
  push:
    tags:
      - "v*"
      
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tile-floorplan-card.js
            tile-floorplan-card-editor.js
          token: ${{ secrets.RELEASE_TOKEN }}
